version: '3.8'

services:
  postgres:
    image: alexshigida/rest-service:postgres
    container_name: postgres
    build:
      dockerfile: ./postgres/Dockerfile
    ports:
      - ${POSTGRES_EXT_PORT}:${POSTGRES_INT_PORT}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - hls-net
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-logs:/var/log/postgresql
    restart: always

  hls:
    image: alexshigida/rest-service:hls
    container_name: hls
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - postgres
    env_file:
      - .env
    ports:
     - ${PORT}:${PORT}
    volumes:
      - hls-src:/usr/hls/src:rw
      - hls-prisma:/usr/hls/prisma:rw
      - /usr/hls/node_modules
    networks:
      - hls-net
    restart: always

volumes:
  hls-src:
    driver: local
    driver_opts:
      type: none
      device: ./src
      o: bind
  hls-prisma:
    driver: local
    driver_opts:
      type: none
      device: ./prisma
      o: bind
  pg-data:
  pg-logs:

networks:
  hls-net:
    driver: bridge